services:
  postgres:
    container_name: "postgres-dev"
    image: "postgres:16.0-alpine3.18"
    env_file:
      - ../.env.development
    ports:
      - "5432:5432"
  mongodb:
    container_name: "mongodb-dev"
    image: "mongo:8.0"
    env_file:
      - ../.env.development
    ports:
      - "27017:27017"
  mailcatcher:
    container_name: "mailcatcher-dev"
    image: "sj26/mailcatcher"
    ports:
      - "1025:1025"
      - "1080:1080"
